### ISSUE TITLE
Cliqz Test Pilot isn't working on latest Beta 57.0b9 and latest Nightly (58.0a1) builds

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [cliqz-oss/browser-core#54] opened 2017-10-18 15:39 UTC
[Notes]:
- This issue is not reproducible on Firefox Release 56.0.
- Cliqz appears as enabled in "about:addons" page, but its functionality is not present in the browser. 

[Affected versions]:
- Firefox 57 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have the "extensions.legacy.enabled" boolean pref to "true" on a new clean profile.
- Have the Test Pilot add-on installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites
2. Enable Cliqz experiment from "https://testpilot.firefox.com/experiments/cliqz" page. 
3. Open a new tab and observe the displayed page.
4. Type something on the URL bar and observe the suggestions.

[Expected result]:
Step 3: The Cliqz new tab is displayed.
Step 4: The Cliqz search suggestions are displayed.

[Actual result]:
Step 3: The Activity Stream new tab page is displayed.
Step 4: The default Firefox suggestions are displayed.

[Regression]
- In order to find out what might have caused this issue I’ve ran the Mozregression tool. 
Here are the results:
Last good revision: 45d8844f012430cd8826fdb18f1f11be76071b2d
First bad revision: c0b4c13955e71735654c4bf53186eca801e5e461
18:01.64 INFO: Pushlog: https://goo.gl/EcsaR6

From the pushlog, it seems that the bug 1371395 has caused this. 

[Additional Notes]:
- Here is a screen recording with the issue:
![cliqz](https://user-images.githubusercontent.com/31244235/31727935-a43fbdec-b433-11e7-87df-58db5229dad0.gif)

**Comment by past** [comment] 2017-10-18 16:25
The regression range can't be right, these are test-only changes.

**Comment by SoftVision-CosminMuntean** [comment] 2017-10-18 16:33
We will try again to find a regression range and we will provide the results.

**Comment by SoftVision-CosminMuntean** [comment] 2017-10-19 09:02
I have performed again a regression range and I got a different result:

Last good revision: 40a865254b3284177bc80675c2f3198cd875192d
First bad revision: a47fcbb0b15fbefafc5b760edf59d9fed903aa30
Pushlog: https://goo.gl/x3dNGL

From this pushlog, looks like the[ bug 1389529](https://bugzilla.mozilla.org/show_bug.cgi?id=1389529) might cause this issue. 
@past can you please take a look at this?

**Comment by past** [comment] 2017-10-19 09:09
That seems plausible, yes. Thank you!

**Comment by luciancor** [comment] 2018-06-04 09:58
This issue should be fixed in our latest builds. Closing this issue for now but please let me know if anything else is required from our side

**Closed by luciancor** 2018-06-04 09:58 UTC
